server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: brand-service
          uri: http://localhost:6868
          predicates:
            - Path=${app.api-prefix}/brand/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://localhost:8386
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=1
